const contentActions = (function() {
    const START_CHANGE_TAB_ACTION = 'START_CHANGE_TAB_ACTION';
    const CHANGE_TAB_ACTION_FAILURE = 'CHANGE_TAB_ACTION_FAILURE';
    const CHANGE_TAB_ACTION_SUCCESS = 'CHANGE_TAB_ACTION_SUCCESS';

    return {
        START_CHANGE_TAB_ACTION,
        CHANGE_TAB_ACTION_FAILURE,
        CHANGE_TAB_ACTION_SUCCESS,
    }
})();